### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by enricobenedos** [aloisdeniel/vsts-flutter-tasks#31]
Good morning, 
I'm trying to build my Flutter project with Azure DevOps with this beautiful extension but during the build task I receive this error:
```
##[section]Starting: FlutterBuild
==============================================================================
Task         : Flutter Build
Description  : Build a Flutter application project.
Version      : 0.2.21
Author       : Aloïs Deniel
Help         : [More Information](https://github.com/aloisdeniel/vsts-flutter-tasks)
==============================================================================
cd: no such file or directory: /Users/vsts/agent/2.158.0/work/1/s/coin_flip_app

##[error]Error: Failed cd: cd: no such file or directory: /Users/vsts/agent/2.158.0/work/1/s/coin_flip_app

##[section]Finishing: FlutterBuild
```
This is my pipeline:
```
trigger:
- master
- develop

# Flutter build

variables:
  projectDirectory: coin_flip_app

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-10.13'
      
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)
```
It is clear that it does not find the project folder. But for me it is not clare what is the correct value to write on `projectDirectory`.
