### ISSUE TITLE
“Version could not be created from build. Please make sure that your .ipa file has the correct format”

### ISSUE THREAD

**Issue by liloSc** [aloisdeniel/vsts-flutter-tasks#32]
Everything works fine for the Android Release of the Application. I'm developing the app with Flutter, then I'm building it with Azure DevOps and finally I'm publishing it to the AppCenter.

In contrast to Android, IOS does not create an IPA file but only builds a Runner.app. So in Azure DevOps i'm getting the ipa with following code: 

```
mkdir -p Payload
mv ./build/ios/iphoneos/Runner.app Payload
zip -r -y Payload.zip Payload/Runner.app
mv Payload.zip Payload.ipa
rm -Rf Payload
```

I can build it, but unfortunately when I do the same for IOS I'm getting this **Error**: 

> 6851704Z ##[error]"{\"status\":\"error\",\"message\":\"Version could not be created from build. Please make sure that your .ipa file has the correct format.\"}"
    http response code: 422

So something is wrong with my ipa. Is there any other possibility to create the ipa from the Runner.app in Azure DevOps?

**Comment by aloisdeniel** [comment]
Hello,

I'm using those taks on my side. There's two consecutive builds, but at least it works ...

```yaml

  - task: YamlWriter@0
    displayName: 'Update pubspec'
    inputs:
      file: 'pubspec.yaml'
      set: version='${{ parameters.package_version }}+300000$(Build.BuildId)'

  - task: ios-bundle-version@1
    displayName: 'Update Info.plist'
    inputs:
      sourcePath: 'ios/Runner/Info.plist'
      versionCodeOption: 'buildid'
      versionCode: '300000$(Build.BuildId)'
      versionName: '${{ parameters.package_version }}'
      printFile: true

  - task: FlutterBuild@0
    displayName: 'Flutter Build app (iOS)'
    inputs:
      target: 'ios'
      buildFlavour: prod
      entryPoint: lib/main_prod.dart
      buildNumber: '300000$(Build.BuildId)'
      buildName: '${{ parameters.package_version }}'

  - task: Bash@3
    displayName: 'Prepare an App Store package'
    inputs:
      targetType: 'inline'
      script: |
        xcodebuild -workspace ios/Runner.xcworkspace -scheme prod -sdk iphoneos -configuration Release-prod archive -archivePath build/ios/Runner.xcarchive
        xcodebuild -exportArchive -archivePath build/ios/Runner.xcarchive -exportOptionsPlist ci/ExportOptions.plist -exportPath build/ios/App-${{ parameters.package_version }}.ipa
  
```
