### ISSUE TITLE
ios build seems to be stuck

### ISSUE THREAD

**Issue by michaelgobbers** [aloisdeniel/vsts-flutter-tasks#35]
Hi. Thanks for putting in the effort of creating this project.

I was able to successfully build my flutter app on azure devops with it and setup a CD pipline to testflight. However, once in a while my builds keep on running and time out after the default 60 minute limit. It seems that the iOS build step seems to be stuck and loops infinitely until the timeout.

my build step:

```
#Your build pipeline references an undefined variable named BuildID. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
task: aloisdeniel.flutter.flutter-build.FlutterBuild@0
  displayName: 'Flutter Build ios'
  inputs:
    target: ios
    buildName: '1.0.$(BuildID)'
    iosCodesign: false
  condition: succeededOrFailed()
```

build-output:
```
Starting: Flutter Build ios
==============================================================================
Task         : Flutter Build
Description  : Build a Flutter application project.
Version      : 0.2.21
Author       : Aloïs Deniel
Help         : [More Information](https://github.com/aloisdeniel/vsts-flutter-tasks)
==============================================================================
/Users/runner/hostedtoolcache/Flutter/1.9.1/macos/flutter/bin/flutter build ios --no-codesign --build-name=1.0.$(BuildID) --build-number=164634
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.rydoo.mobile for device (ios-release)...
##[error]The operation was canceled.
Finishing: Flutter Build ios

```
