### ISSUE TITLE
Pass flutter build number from pubspec.yaml to build task

### ISSUE THREAD

**Issue by gdagitrep** [aloisdeniel/vsts-flutter-tasks#43]
Thanks for the hard work of creating 'build' tasks. ❤️ 
Right now, the default value of build number is $(Build.BuildNumber), which is an azure pipeline predefined variable, as mentioned [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables), and evaluates to currentdate in {yyyymmdd}.{iteration_today} , for example: 20200308.10 --> referring to 10th build today.

This works well without issues, but I want to use build number and name from the pubspec.yaml. One way would be to export them as environment variable, but don't know how.

**Comment by gdagitrep** [comment]
Actually, if you keep the buildNumber and buildName empty for the build task, the build takes them from  pubspec.yaml (or local.properties) file. 
```
task: FlutterBuild@0
      inputs:
        target: aab
        buildNumber:
        buildName:
        projectDirectory: $(projectDirectory)
```
