### ISSUE TITLE
VSTS Flutter Web

### ISSUE THREAD

**Issue by liloSc** [aloisdeniel/vsts-flutter-tasks#63]
**How can i run a Build Pipeline with just Web as the target Platform?**

For now i have this in my yaml File
```
trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

- task: FlutterBuild@0
  inputs:
    target: 'web'
    projectDirectory: '.'
```

But then i get the following Error Message: 
`"build web" is not currently supported.`

I already tried to change the Build Task to this 
```
- task: CmdLine@2
  inputs:
    script: |
      $(FlutterToolPath)/flutter config --enable-web 
      $(FlutterToolPath)/flutter create .
      $(FlutterToolPath)/flutter build web
```

But i get the same Error..
