### ISSUE TITLE
Complete example to publish into playstore and apple store

### ISSUE THREAD

**Issue by ductranit** [aloisdeniel/vsts-flutter-tasks#72]
Hi there,
I wonder is there any complete example that run pipeline from build github repo to deploy into playtore & apple store?
I tried to use [google play](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play) and [apple store](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store) extensions
**It's very hard for me to set it up because I can't find any fully document about it**.
Here is my try with ios build first:
```
# Flutter build
name: $(Date:yyyyMMdd)$(Rev:r)
variables:
  projectDirectory: .
trigger:
- deployment  

jobs:
  - job: Build
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'dev'
        version: 'latest'
    - task: CmdLine@2
      displayName: 'Update packages'
      inputs: 
        script: '$(FlutterToolPath)/flutter packages upgrade'
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: '[my_cert.p12]'
        certPwd: '[password]'
        keychain: 'temp'
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: '[my_profile.mobileprovision]'        
    - task: FlutterBuild@0
      inputs:
        target: ios
        projectDirectory: $(projectDirectory)
        iosCodesign: false    
    - task: CopyFiles@2
      inputs:
        contents: '/ios/iphoneos/Runner.app'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'store'
    - task: AppStoreRelease@1
      inputs:
        serviceEndpoint: 'itunes connection'
        appIdentifier: '[app_bundle]'
        appType: 'iOS'
        releaseTrack: 'TestFlight'
        shouldSkipWaitingForProcessing: true
        shouldSkipSubmission: true
        appSpecificId: '[my_app_id]'
        teamId: '[my_team_id]'
        teamName: '[my_team_name]'
```

At the moment I have trouble on the CopyFiles task, it says `found 0 files`.
And the problem is that I don't know whether I'm doing correctly or not.
Is there anyone that succeeded to publish into playstore & apple store with azure pipeline? 
Can you please share the yml setup?
Thanks!
