### ISSUE TITLE
Error "build web" is not currently supported on task FlutterBuild@0

### ISSUE THREAD

**Issue by zaidas1m** [aloisdeniel/vsts-flutter-tasks#73]
I have set up Flutter to use channel beta with config --enable-web as follow:
```
jobs:
- job: Build
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: FlutterInstall@0
    displayName: Setup flutter
    inputs:
      channel: 'beta'
      version: 'latest'

  - task: FlutterCommand@0
    displayName: 'Flutter upgrade'
    inputs:
      arguments: 'upgrade'

  - task: FlutterCommand@0
    displayName: 'Flutter Enable Web'
    inputs:
      arguments: 'config --enable-web'

  - task: FlutterBuild@0
    inputs:
      target: web
      projectDirectory: '.' 
```
But I'm getting error in task `FlutterBuild@0`:
```
"build web" is not currently supported.
##[error]Error: The process '/Users/runner/hostedtoolcache/Flutter/1.26.0-17.3.pre-beta/macos/flutter/bin/flutter' failed with exit code 1
```
 What I'm doing wrong?

I tried using:
```
- task: FlutterCommand@0
    inputs:
      arguments: 'build web'

```
instead of Task `FlutterBuild@0` but doesn't create or build any file.

Any help?

Thanks!

**Comment by zaidas1m** [comment]
Well, thanks to #72 I found the solution. Instead of using Task `FlutterCommand@0` to upgrade and enable web, to use Task `CmdLine@2`.
This is my final pipeline if someone needs it:
```
trigger:
- develop

jobs:
- job: Build
  pool:
    vmImage: 'macOS-latest'

  steps:
  - task: FlutterInstall@0
    displayName: Setup flutter
    inputs:
      channel: 'beta'
      version: 'latest'

  - task: CmdLine@2
    displayName: 'Update packages'
    inputs: 
      script: '$(FlutterToolPath)/flutter packages upgrade'

  - task: CmdLine@2
    displayName: 'Config enable web'
    inputs: 
      script: '$(FlutterToolPath)/flutter config --enable-web'

  - task: FlutterBuild@0
    inputs:
      target: web
      projectDirectory: '.'
    
  - task: CopyFiles@2 
    displayName: 'Copy Files to www'
    inputs:
      SourceFolder: 'build/web'
      TargetFolder: 'www'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish web artifact'
    inputs:
      pathtoPublish: 'www'
      artifactName: 'web'
```
