### ISSUE TITLE
Xcode Build missingTarget

### ISSUE THREAD

**Issue by ced455** [aloisdeniel/vsts-flutter-tasks#74]
Hello there, I am trying to create the IPA fail to releasemy app in the Apple app store but i am stuck with this error :

```
Starting: Xcode

Task         : Xcode
Description  : Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
Version      : 5.179.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/xcode

/usr/bin/xcodebuild -version
Xcode 12.3
Build version 12C33
/usr/bin/xcodebuild -configuration Release -workspace /Users/runner/work/1/s/ios/Runner.xcodeproj/project.xcworkspace -scheme Runner archive -verbose CODE_SIGNING_ALLOWED=NO | /usr/local/lib/ruby/gems/2.7.0/bin/xcpretty -r junit --no-color

❌  error: Build service could not start build operation: unknown error while handling message: missingTarget(guid: "a40ea2d289f72f0ad44412f65b07ce7188a783a885d8b0b3beb2e9f90bde3f49")


** ARCHIVE FAILED **

##[error]Error: /usr/bin/xcodebuild failed with return code: 65
```

------------------------------------------------------------------------------

This is my pipeline config :

 ```
name: $(BuildID)

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:

- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'


- task: FlutterBuild@0
  inputs:
    target: 'ios'
    projectDirectory: '.'
    iosCodesign: false
    iosTargetPlatform: device

- task: Xcode@5
  inputs:
    actions: 'archive'
    configuration: 'Release'
    sdk: 'iphoneos'
    scheme: 'Runner'
    packageApp: false
    args: '-verbose' 
```

I am able to build from my mac with no problem.
I can also build the Android .aab package an ship it.

I am trying to understant what "missingTarget" the error is talking about, is anyone have any experience with that ?

Thank you
