### ISSUE TITLE
Build task does not support --dart-define

### ISSUE THREAD

**Issue by maks** [aloisdeniel/vsts-flutter-tasks#80]
There is currently no way to specify `--dart-define` for the Build task.

**Comment by maks** [comment]
I should say its easy enough to define a custom task to do this:
```
- task: CmdLine@2
    displayName: "Android build"
    inputs:
          script: "$(FlutterToolPath)/flutter build appbundle --dart-define MY_CONFIG=FooBar"
```
but it would be nice to have this supported in the built-in FlutterBuild task.
