### ISSUE TITLE
Flutter flavors doesn't work with iOS build on simulator

### ISSUE THREAD

**Issue by hossameldinmi** [aloisdeniel/vsts-flutter-tasks#83]
```
trigger:
  - master
  - develop

pool:
  vmImage: "macOS-latest"
jobs:
  - job: status
    steps:
    - checkout: self # self represents the repo where the initial Pipelines YAML file was found
      clean: true # whether to fetch clean each time
      submodules: recursive # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
      persistCredentials: true # set to 'true' to leave

    - task: fca8d27d-85f4-4d5d-a519-8d7a7edf15d7@0
      displayName: Flutter Install
      inputs:
        channel: 'stable'
        version: 'custom'
        customVersion: '1.22.6'
   
    - task: 1416022c-c995-4e2c-85ec-0cd88e54a2b0@0
      displayName: Pub get
      inputs:
        projectDirectory:  $(PROJ_DIR)
        arguments: 'pub get'

    - task: 10a2efb1-b922-4849-81de-bccd2537ccc1@0
      displayName: flavor1 Build iOS (IPA)
      inputs:
        target: 'ios'
        projectDirectory: $(PROJ_DIR)
        buildFlavour: flavor1
        entryPoint: $(entry_point)
        buildNumber: 
        iosTargetPlatform: 'simulator'
        iosCodesign: false
      continueOnError: true
```
console output
```==============================================================================
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
/Users/runner/hostedtoolcache/Flutter/1.22.6-stable/macos/flutter/bin/flutter build ios --simulator --debug --target=$(##entry_point##)
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2559) Warning: Use Cipheriv for counter mode of aes-256-ctr
Downloading ios tools...                                            7.8s
Downloading ios-profile tools...                                    4.1s
Downloading ios-release tools...                                   23.4s

The Xcode project defines schemes: flavor1, flavor2, flavor3
You must specify a --flavor option to select one of the available schemes.
##[error]Error: The process '/Users/runner/hostedtoolcache/Flutter/1.22.6-stable/macos/flutter/bin/flutter' failed with exit code 1
Finishing: flavor1 Build iOS (IPA)```
